name: Yao Lu

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown

url: https://yaolubrain.github.io
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra
